<?php

namespace MFB\CmsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PressReleaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PressReleaseRepository extends EntityRepository
{
}